:terms:
    - :term: 'School of Arts and Sciences'
      :id: 'School of Arts and Sciences'
    - :term: 'The Fletcher School'
      :id: 'The Fletcher School'
    - :term: 'School of Engineering'
      :id: 'School of Engineering'
    - :term: 'School of Nutrition'
      :id: 'School of Nutrition'
    - :term: 'School of Medicine'
      :id: 'School of Medicine'
    - :term: 'School of Veterinary Medicine'
      :id: 'School of Veterinary Medicine'
    - :term: 'School of Dental Medicine'
      :id: 'School of Dental Medicine'